test_upper_case_names (__main__.TestExercice) ... ERROR

======================================================================
ERROR: test_upper_case_names (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 17, in test_upper_case_names
    output = list(map(exercice.majuscule, self.words))
  File "/home/runner/work/c03_ch2_ecriture-Shahyan923/c03_ch2_ecriture-Shahyan923/exercice.py", line 5, in majuscule
    for lettre in mot:
NameError: name 'mot' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
